CREATE TABLE final_GRUPO(
    IDGRUPO int(1) check (idgrupo in (0,1,2,3,4,5,6)),
    NOMBRE_MUSCULO VARCHAR(20) NOT NULL,

    CONSTRAINT PK_IDGRUPO PRIMARY KEY(IDGRUPO)
);

CREATE TABLE final_EJERCICIO(
    IDEJERCICIO INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRE_EJERCICIO VARCHAR(20) NOT NULL,
    MUSCULO int(1) NOT NULL,
    NIVEL_EJERCICIO VARCHAR(20) NOT NULL CHECK (NIVEL_EJERCICIO in ('Principiante', 'Intermedio', 'Avanzado')),
    DESCRIPCION VARCHAR(500) NOT NULL,
    IDFOTO VARCHAR(10) NOT NULL,

    CONSTRAINT PK_EJERCICIO PRIMARY KEY(IDEJERCICIO),
    CONSTRAINT FK_MUSCULO FOREIGN KEY (MUSCULO) REFERENCES final_GRUPO(IDGRUPO) ON DELETE CASCADE
);


CREATE TABLE final_RUTINA(
    IDRUTINA INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRE_RUTINA VARCHAR(20) NOT NULL,
    IDGRUPO int(1) NOT NULL,
    IDUSUARIO VARCHAR(10) NOT NULL,
    INTERVALO_TIEMPO int(10) DEFAULT 180,
    NIVEL_RUTINA VARCHAR(20) NOT NULL CHECK (NIVEL_RUTINA in ('Principiante', 'Intermedio', 'Avanzado')),

    CONSTRAINT PK_IDRUTINA PRIMARY KEY(IDRUTINA),
    CONSTRAINT FK_IDGRUPO FOREIGN KEY (IDGRUPO) REFERENCES final_GRUPO(IDGRUPO) ON DELETE CASCADE
);


CREATE TABLE final_EJERCICIO_RUTINA(
    IDRUTINA int(10),
    IDEJERCICIO int(10),

    CONSTRAINT PK_EJERCICIO_RUTINA PRIMARY KEY (IDRUTINA,IDEJERCICIO),
    CONSTRAINT FK_IDRUTINA FOREIGN KEY (IDRUTINA) REFERENCES final_RUTINA(IDRUTINA) ON DELETE CASCADE,
    CONSTRAINT FK_IDEJERCICIO FOREIGN KEY (IDEJERCICIO) REFERENCES final_EJERCICIO(IDEJERCICIO) ON DELETE CASCADE

);


CREATE TABLE final_USUARIO(
    NICKNAME VARCHAR(20),
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20) DEFAULT NULL,
    CORREO VARCHAR(50) NOT NULL,
    CONTRASEÑA VARCHAR(50) NOT NULL,
    SEXO VARCHAR(4) NOT NULL CHECK (SEXO in ('H', 'M', 'Otro', 'PND')),
    FOTO VARCHAR(30) DEFAULT NULL,
    CONSTRAINT PK_NICKNAME_USUARIO PRIMARY KEY (NICKNAME)

);




CREATE TABLE final_VALORACION(
    IDRUTINA INT(10) NOT NULL AUTO_INCREMENT,
    VALORACION int(1) DEFAULT NULL CHECK (VALORACION IN (0,1,2,3,4,5)),
    NICKNAME VARCHAR(20),

    CONSTRAINT PK_VALORACION PRIMARY KEY (IDRUTINA,NICKNAME),
    CONSTRAINT FK_IDRUTINA_VALORACION FOREIGN KEY (IDRUTINA) REFERENCES final_RUTINA(IDRUTINA) ON DELETE CASCADE,
    CONSTRAINT FK_NICKAME_VALORACION FOREIGN KEY (NICKNAME) REFERENCES final_USUARIO(NICKNAME) ON DELETE CASCADE
);

CREATE TABLE final_TEMA(
    IDTEMA INT(10) NOT NULL AUTO_INCREMENT,
    NICKNAME VARCHAR(20),
    FECHA_PUBLICACION TIMESTAMP DEFAULT NOW(),
    NOMBRE VARCHAR(50) NOT NULL,
    CONTENIDO VARCHAR(500) NOT NULL,
    CONSTRAINT PK_IDTEMAS PRIMARY KEY (IDTEMA),
    CONSTRAINT FK_NICKNAME_TEMA FOREIGN KEY (NICKNAME) REFERENCES final_USUARIO(NICKNAME) ON DELETE CASCADE
);

CREATE TABLE final_MENSAJE(
    IDMENSAJE INT(10) NOT NULL AUTO_INCREMENT,
    NICKNAME VARCHAR(20) NOT NULL,
    IDTEMA int(10) NOT NULL,
    CONTENIDO VARCHAR(500) DEFAULT NULL,
    FECHA_PUBLICACION_MENSAJE TIMESTAMP DEFAULT NOW(),
    CONSTRAINT PK_IDMENSAJE PRIMARY KEY (IDMENSAJE),
    CONSTRAINT FK_IDTEMA_MENSAJE FOREIGN KEY (IDTEMA) REFERENCES final_TEMA(IDTEMA) ON DELETE CASCADE
);

CREATE TABLE final_MENSAJES_SECUNDARIOS(
    IDMENSAJE_SECUNDARIO INT(10) NOT NULL AUTO_INCREMENT,
    IDMENSAJE INT(10) NOT NULL,
    IDTEMA INT(10) NOT NULL,
    NICKNAME VARCHAR(20) NOT NULL,
    CONTENIDO VARCHAR(500) DEFAULT NULL,
    FECHA_PUBLICACION_MENSAJE TIMESTAMP DEFAULT NOW(),

    CONSTRAINT PK_IDMENSAJE_SECUNDARIO PRIMARY KEY (IDMENSAJE_SECUNDARIO),
    CONSTRAINT FK_IDMENSAJE_SECUNDARIO_USUARIO FOREIGN KEY (NICKNAME) REFERENCES final_USUARIO(NICKNAME) ON DELETE CASCADE,
    CONSTRAINT FK_IDMENSAJE_SECUNDARIO_TEMA FOREIGN KEY (IDTEMA) REFERENCES final_TEMA(IDTEMA) ON DELETE CASCADE,
    CONSTRAINT FK_IDMENSAJE_SECUNDARIO FOREIGN KEY (IDMENSAJE) REFERENCES final_MENSAJE(IDMENSAJE) ON DELETE CASCADE
);

CREATE TABLE final_LIKES_TEMA(
    IDTEMA int(10),
    NICKNAME VARCHAR(20),

    CONSTRAINT PK_LIKES_MENSAJE PRIMARY KEY (IDTEMA,NICKNAME),
    CONSTRAINT FK_IDMTEMA FOREIGN KEY (IDTEMA) REFERENCES final_TEMA(IDTEMA) ON DELETE CASCADE,
    CONSTRAINT FK_NICKNAME FOREIGN KEY (NICKNAME) REFERENCES final_USUARIO(NICKNAME) ON DELETE CASCADE

);

CREATE TABLE final_PUBLICACION(
    IDPUBLICACION INT(10) NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(50) NOT NULL,
    FECHA_PUBLICACION TIMESTAMP DEFAULT NOW(),
    CONTENIDO VARCHAR(500) NOT NULL,
    AUTOR VARCHAR(50) NOT NULL,


    CONSTRAINT PK_IDPUBLICACION PRIMARY KEY (IDPUBLICACION)
);
