INSERT INTO final_BK_ADMINISTRADORES (NOMBRE,APPELLIDO1,APPELLIDO2,CORREO,PASSWORDA)
    VALUES ('Jhonny','Chicaiza','Palomo','jhonnyfc88@gmail.com','123456');
INSERT INTO final_BK_ADMINISTRADORES (NOMBRE,APPELLIDO1,APPELLIDO2,CORREO,PASSWORDA)
    VALUES ('Dani','Del BArrio','Farran','danieldbg1@gmail.com','123456');
