CREATE TABLE final_BK_ADMINISTRADORES(
    ID_ADMIN    INTEGER AUTO_INCREMENT,
    NOMBRE      VARCHAR(20) NOT NULL,
    APPELLIDO1  VARCHAR(20) NOT NULL,
    APPELLIDO2  VARCHAR(20),
    CORREO      VARCHAR(40) NOT NULL UNIQUE,
    PASSWORDA   VARCHAR(255) NOT NULL,
    FECH_ALTA   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PK_ADMIN PRIMARY KEY (ID_ADMIN));
