CREATE TABLE final_BK_ADMINISTRADORES(
    ID_ADMIN    INTEGER,
    NOMBRE      VARCHAR(20) NOT NULL,
    APPELLIDO1  VARCHAR(20) NOT NULL,
    APPELLIDO2  VARCHAR(20),
    CORREO      VARCHAR(30) NOT NULL UNIQUE,
    PASSWORDA   VARCHAR(260) NOT NULL,
    FECH_ALTA   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PK_ADMIN PRIMARY KEY (ID_ADMIN));

INSERT INTO final_BK_ADMINISTRADORES (ID_ADMIN,NOMBRE,APPELLIDO1,APPELLIDO2,CORREO,PASSWORDA)
    VALUES (1,'Jhonny','Chicaiza','Palomo','jhonnyfc88@gmail.com','123456');